# Full project: https://gitlab.com/pages/hexo
image: node:6.10.0

pages:
  script:
  - npm install

  - npm install --save hexo-admin
  - npm install hexo-renderer-less --save
  - npm install hexo-generator-feed --save
  - npm install hexo-generator-json-content --save
  - npm install hexo-helper-qrcode --save
  - npm install hexo-wordcount --save
  - npm install hexo-abbrlink --save
  - npm install hexo-filter-github-emojis --save

  - ./node_modules/hexo/bin/hexo generate
  artifacts:
    paths:
    - public
  cache:
    paths:
      - node_modules
    key: project
  only:
  - master